version: "3.1"

#--------------------------------------------------------------------------------------
#- Ping Identity integrated demo
#-
#-     app    console  
#-     443    9000     
#-      |      |       
#-   +----------------+
#-   |   PingAccess   |
#-   +----------------+
#-
#-     login  console            app                console           rest    ldaps
#-     9031   9999               9022                 8443            1443    1636
#-      |      |                  |                    |               |       |
#-   +---------------+    +---------------+    +---------------+    +---------------+
#-   | PingFederate  |    |  PingCentral  |    |PingDataConsole|    | PingDirectory |
#-   +---------------+    +---------------+    +---------------+    +---------------+
#-
#-   +-----------------------+--------------------------------------------------------+
#-   |  Product Console/App  |  URL                                                   |
#-   |                       |    username: administrator                             |
#-   |                       |    password: 2FederateM0re                             |
#-   +-----------------------+--------------------------------------------------------+
#-   |  PingAccess           |  https://localhost:9000/                               |
#-   |  PingFederate         |  https://localhost:9999/pingfederate/app               |
#-   |  PingDirectory        |  https://localhost:8443/   (Server=pingdirectory)      |
#-   |  PingCentral          |  https://localhost:9022/                               |
#-   +-----------------------+--------------------------------------------------------+
#--------------------------------------------------------------------------------------

services:
  pingaccess:
    image: pingidentity/pingaccess@sha256:c551a2d54f26947ce12399e8f4ecb70271b605e1a004bd9a6e65818accdda38d
    command: wait-for pingfederate:9031 -t 420 -- entrypoint.sh start-server
    environment:
      # **** SERVER PROFILES BEGIN ****
      # Server Profile - Product License
      - SERVER_PROFILE_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=lbg-layered-profiles/license/pingaccess
      - SERVER_PROFILE_PARENT=EXTENSIONS

      # Server Profile - Extensions
      - SERVER_PROFILE_EXTENSIONS_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_EXTENSIONS_PATH=lbg-layered-profiles/extensions/pingfederate
      - SERVER_PROFILE_EXTENSIONS_PARENT=LBG
      
      # Base Server Profile
      - SERVER_PROFILE_LBG_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_LBG_PATH=lbg/pingaccess
      - PA_ENGINE_PUBLIC_HOSTNAME=ping.lloydstsb.com
      - PA_ADMIN_PUBLIC_HOSTNAME=ping.lloydstsb.com
      - PA_LOG_LEVEL=DEBUG
      # **** SERVER PROFILE END **** 
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ~/.pingidentity/devops
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/full-stack.pingaccess:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/lbg/pingaccess:/opt/in
    ports:
      - 443:443
      - 9000:9000
    networks:
      - pingnet-dmz

  pingfederate:
    image: pingidentity/pingfederate@sha256:5306cef0b44bb215625055581a320437b08bf2824cbaf8fc8fdc91d09f4e3fff
    command: wait-for pingdirectory:389 -t 720 -- entrypoint.sh start-server
    environment:
      # **** SERVER PROFILES BEGIN ****
      # Server Profile - Data
      - SERVER_PROFILE_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=lbg-layered-profiles/config/pingfederate
      - SERVER_PROFILE_PARENT=LICENSE

      # Server Profile - Product License
      - SERVER_PROFILE_LICENSE_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_LICENSE_PATH=lbg-layered-profiles/license/pingfederate
      - SERVER_PROFILE_LICENSE_PARENT=EXTENSIONS

      # Server Profile - Extensions
      - SERVER_PROFILE_EXTENSIONS_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_EXTENSIONS_PATH=lbg-layered-profiles/extensions/pingfederate
      - SERVER_PROFILE_EXTENSIONS_PARENT=LBG
      
      # Base Server Profile
      - SERVER_PROFILE_LBG_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_LBG_PATH=lbg/pingfederate
      - USER_BASE_DN=dc=lloydstsb,dc=com
      - PF_ENGINE_PUBLIC_HOSTNAME=ping.lloydstsb.com
      - PF_ADMIN_PUBLIC_HOSTNAME=ping.lloydstsb.com
      # **** SERVER PROFILE END ****
    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/lbg/pingfederate:/opt/in
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingdirectory:
    image: pingidentity/pingdirectory@sha256:b8261fdff6b820314a28a9e111a0d35ec96bd9fc8938a262108e1049a4e97ca8
    environment:
      # **** SERVER PROFILES BEGIN ****
      # Server Profile - Product License
      - SERVER_PROFILE_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=lbg-layered-profiles/license/pingdirectory
      - SERVER_PROFILE_PARENT=LBG

      # Base Server Profile
      - SERVER_PROFILE_LBG_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_LBG_PATH=lbg/pingdirectory
      - USER_BASE_DN=dc=lloydstsb,dc=com
      - PD_ENGINE_PUBLIC_HOSTNAME=ping.lloydstsb.com
      - PF_ENGINE_PUBLIC_HOSTNAME=ping.lloydstsb.com
      - PA_ENGINE_PUBLIC_HOSTNAME=ping.lloydstsb.com
      # **** SERVER PROFILE END ****
    env_file:
      - ~/.pingidentity/devops
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/lbg/pingdirectory:/opt/in
    ports:
      - 1636-1646:636
      - 1443-1453:443
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole@sha256:476e69d84bf3dc0085ebe2cf5473468f9a87ec7d2be5475924cd6f93463716c7
    ports:
      - 8443:8443
    networks: 
      - pingnet-internal

  pingcentral:
    image:  pingidentity/pingcentral@sha256:5c82b242d047c7ac7fcd5af2c0c1190bfdd4b92e1d94a64e848511198ed9838b
    command: wait-for pingcentral-db:3306 -t 7200 -- entrypoint.sh start-server
    environment:
      # **** SERVER PROFILES BEGIN ****
      # Server Profile - Product License
      - SERVER_PROFILE_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=lbg-layered-profiles/license/pingcentral
      - SERVER_PROFILE_PARENT=LBG

      # Base Server Profile
      - SERVER_PROFILE_LBG_URL=https://github.com/stewcowie/pingidentity-server-profiles.git
      - SERVER_PROFILE_LBG_PATH=lbg/pingcentral/external-mysql-db
      - PING_CENTRAL_BLIND_TRUST=true
      - PING_CENTRAL_VERIFY_HOSTNAME=false
      - MYSQL_USER=root
      - MYSQL_PASSWORD=2FederateM0re
      - MYSQL_SERVICE_HOST=pingcentral-db
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_DATABASE=pingcentral
      # **** SERVER PROFILE END ****
    env_file:
      - ${HOME}/.pingidentity/devops
    ports:
      - "9022:9022"
    depends_on:
      - "pingcentral-db"
    networks:
      - pingnet-internal

  pingcentral-db:
    image: mysql@sha256:0ba38ea9c478d1e98b2f0bc0cee5a62345c9f06f78c4b48123bdc70d8d224686
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 2FederateM0re
    ports:
      - "3306:3306"
    networks:
      - pingnet-internal
           
networks:
    pingnet-internal:
    pingnet-dmz: